# 워크플로우 이름
name: "Chromatic Publish"

# 워크플로우를 위한 이벤트
on: push

# 작업 목록
jobs:
  chromatic:
    runs-on: ubuntu-latest # 작업을 실행할 OS
    steps: # 작업 단계
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Run Chromatic
        uses: chromaui/action@latest
        with: # GitHub Action 에 필요한 옵션
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
